language: node_js
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0'
  - 'export PATH=$HOME/.yarn/bin:$PATH'
branches:
  only:
    - master
    - feat/v4-for-real-now
sudo: false
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
